name: Publish

on:
    release:
        types: [created]

jobs:
    publish-github:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
                with:
                    ref: ${{ github.ref }}
            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 21
            -   name: Set up PNPM
                uses: pnpm/action-setup@v4
                with:
                    version: 10
            -   name: Check
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: check
            -   name: Build
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: build

            -   name: Upload Jars
                id: upload-release-asset
                uses: svenstaro/upload-release-action@v1-release
                with:
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
                    tag: ${{ github.ref }}
                    file: ./build/libs/*.jar
                    file_glob: true

    publish-maven:
        name: Publish to Maven
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
                with:
                    ref: ${{ github.ref }}
            -   name: Set up JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 21
            -   name: Set up PNPM
                uses: pnpm/action-setup@v4
                with:
                    version: 10
            -   name: Check
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: check
            -   name: Setup GCP
                uses: google-github-actions/setup-gcloud@v0
                with:
                    project_id: ${{ secrets.GCP_PROJECT_ID }}
                    service_account_key: ${{ secrets.GCP_ARTIFACTS_KEY }}
                    export_default_credentials: true
            -   name: Upload to GCP
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: publish

    publish-npm:
        name: Publish to NPM
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}

            - name: Configure NPM
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Set up PNPM
              uses: pnpm/action-setup@v4
              with:
                version: 10

            - name: Install JS dependencies
              working-directory: ./doubleview-react
              run: pnpm install

            - name: Build
              working-directory: ./doubleview-react
              run: pnpm run build

            - name: Publish to NPM
              working-directory: ./doubleview-react
              run: pnpm publish --access=public